### ISSUE TITLE
Update example page to current dates

### ISSUE THREAD

**Issue by StoicLoofah** [StoicLoofah/chronoline.js#18]
The goToToday function doesn't work because today is now off the timeline. It would feel better if it actually worked.

**Comment by Padhraic** [comment]
No idea about baseball. Tried searching Atlanta Braves regular/spring season data but got no where. Can you update this? Also I think this is a bug or enhancement. Shouldn't we auto expand the time line on `goToToday` when no start or end date option are defined and today is outside the event and section dates.

**Comment by StoicLoofah** [comment]
yeah, I can take on this one after we have our next RC out

**Comment by StoicLoofah** [comment]
444d89cae13b75b21b064f8fc01deb4efe0b277c updated both master and gh-pages
