### ISSUE TITLE
How to Get Monday date only per month.

### ISSUE THREAD

**Issue by Arunvelvj** [StoicLoofah/chronoline.js#30]
Is there any option to get monday date only per month.

I need to show only monday or tuesday or else date only per month.
other date don't visible for me.

Help me.

Thank you
Arunvel

**Comment by Padhraic** [comment]
You could implement the `labelInterval` or `hashInterval` options to customize then the ticks and date labels are shown.

     var oneEvent = [ { dates: [new Date(2016, 2, 25)], section: 0 }];
     var timeline1 = new Chronoline(document.getElementById('target1'), oneEvent,
        {
            defaultStartDate: new Date(2011,2,20),
            labelInterval: function(d){
            	if(d.getDay() == 1)
              	    return true;
                // 0 = Sunday, 1 = Monday ..etc 
                return false;
            },
            hashInterval: function(d){
                if(d.getDay() == 1)
              	    return true;
                return false;
            }
        });

I made a jsfiddle example [here](https://jsfiddle.net/chrustlesstulip/s2b0d8f3/)

**Comment by StoicLoofah** [comment]
The answer above should address the problem you described. Does that work for you?

**Comment by Arunvelvj** [comment]
Yes Work Well. Thank you Padhraic.

But, I need to reduce the space between two dates.
Help me.


Thanks you.
Arunvel. L

**Comment by StoicLoofah** [comment]
do you mean the horizontal space between dates? I think the best way to do that is to set the `visibleSpan` on the timeline. You can increase it to crunch the content together

https://github.com/StoicLoofah/chronoline.js/blob/master/chronoline/chronoline.js#L140

**Comment by Padhraic** [comment]
I think @StoicLoofah reply should address this question. If no objection I think we should close this issue.
