### ISSUE TITLE
Tagging & Release & Issues

### ISSUE THREAD

**Issue by Padhraic** [StoicLoofah/chronoline.js#32]
Seems like the tagging is a little out of date. The currently v0.1.1 is pre-release since Aug 2013.

Of the current bugs #6 is performance issue, #12 is IE related, #19 looks like it has a work around. Other issues are quite old.

Here is my suggestion.
1. Update the v0.1.1 pre-release to release.
2. Tag the current master branch as release 0.1.2.
3. When pull request #31 is merged we can tag it v0.1.3-rc
4. We can then tidy up the old issues list, put reproducible bugs into a v0.1.4 milestone

**Comment by StoicLoofah** [comment]
sounds like a plan. do you want to make the tag and release notes for 0.1.2 or should I do it?

**Comment by StoicLoofah** [comment]
Another thing to note with this is that we should be keeping the gh-pages branch up to date with each tagged release as well. I think it's been awhile since I merged the code in there

**Comment by Padhraic** [comment]
I can do the take care of the tagging. I will post in comments or issues about what I am doing. If you spot any issues you can comment and we can adjust. 

The docs will also need to be kept up to date. Maybe add some more api documentation. At the moment that is all written as comments in the code.

**Comment by Padhraic** [comment]
If we clean up the old issues list we can use it as a todo list, assigning to people and release milestones. 
Do you remember the details of those bug issues. Are they something we still need to fix?

**Comment by StoicLoofah** [comment]
I went through and cleaned up old issues. The ones remaining are mostly valid, I think. #12 is something I should look into sooner than. #18 should probably happen before the next release so that the gh-pages is in better shape.

The rest are nice to haves.
