### ISSUE TITLE
qTip2 tunning

### ISSUE THREAD

**Issue by yosva** [StoicLoofah/chronoline.js#34]
Hi! It would be nice if you can allow pass of qTip option in constructor. This will allow tunning of tooltips, in my case I need to always show tooltips, not as popup.

**Comment by StoicLoofah** [comment]
Sure, that makes sense. Do you have a pull request put together for how to do that?

**Comment by Padhraic** [comment]
I think you need to bump the patch number up to 4 (0.1.4) in the package.json before you merge. Other that that is looks ok to me.

**Comment by StoicLoofah** [comment]
Addressed
