### ISSUE TITLE
Right discrete scroll goes left when continuous scrolling is turned off

### ISSUE THREAD

**Issue by sorayadragon** [StoicLoofah/chronoline.js#37]
If continuous scrolling is disabled, the right scroll button actually scrolls left. The error is here: 

https://github.com/StoicLoofah/chronoline.js/blob/1a3dc7be6ec32d4aff904e4cb8e2223605ad7562/chronoline/chronoline.js#L998-L1001

**Comment by StoicLoofah** [comment]
huh, that's a very real bug. thanks for reporting it. can you submit a pull request to fix it as well?

**Comment by Padhraic** [comment]
This issue should be fixed now. Try latest version 0.1.5, bower and npm should be up to date, I will update nuget on Monday when I can use a pc.

`npm i chronoline@0.1.5`

**Comment by StoicLoofah** [comment]
Thanks @Padhraic 

@sorayadragon can you verify that this is working properly for you, and we will close after that?

**Comment by sorayadragon** [comment]
@StoicLoofah Yes, it's working now. Thanks!
