### ISSUE TITLE
Same Tooltip content

### ISSUE THREAD

**Issue by jacopocappelli1989** [StoicLoofah/chronoline.js#48]
Hi,
I have same tooltip content on every part of graph. I check and titles are all different each other.

What I can do to solve?

Thanks,
Jacopo

<img width="733" alt="Schermata 2020-05-11 alle 12 07 00" src="https://user-images.githubusercontent.com/5347335/81550133-1a9fd200-9380-11ea-950e-2115fbf3f593.png">

```
$(document).ready(function() {
                        var timeline = new Chronoline(document.getElementById("target1"), events, {visibleSpan: DAY_IN_MILLISECONDS * 366,
                            animated: true,
                            tooltips: true,
                            defaultStartDate: moment().subtract(300,'days').toDate(),
                            labelInterval: isHalfMonth,
                            hashInterval: isHalfMonth,
                            scrollLeft: prevQuarter,
                            scrollRight: nextQuarter,
                            floatingSubLabels: true,
                        });
```

**Comment by StoicLoofah** [comment]
Sorry, I don't think I quite understand your question. Is the problem that the tooltip isn't changing for each item?

I'm not exactly sure why this issue would be coming up. Could you perhaps put together a test page somewhere for us to look at?

**Comment by StoicLoofah** [comment]
Or perhaps provide more code around what the exact `events` are?
